---
id: 6733bec70d86e13522e98a4f
title: Como a declaração Throw funciona?
challengeType: 19
dashedName: how-does-the-throw-statement-work
---

# --description--

A declaração `throw` em JavaScript é usada para lançar uma exceção definida pelo usuário. Uma exceção em programação é quando um evento inesperado acontece e interrompe o fluxo normal do programa.

Como programadores é importante lidar com essas exceções para que seus programas não travem inesperadamente quando ocorrerem erros. Aqui está a sintaxe básica para a declaração `throw`:

```js
throw expression;
```

A `expression` neste caso seria o objeto ou valor que representa a exceção que você deseja lançar. Exemplos disso seriam as classes de exceção internas como as classes `Error`, `TypeError` e `RangeError`. Aqui está um exemplo de uso da declaração `throw` para lançar um `TypeError`:

```js
function validateNumber(input) {
  if (typeof input !== "number") {
    throw new TypeError("Expected a number, but received " + typeof input);
  }
  return input * 2;
}
```

Neste exemplo, estamos verificando se o tipo de `input` não é do tipo `number`. Se não, então estamos lançando um `TypeError` com uma mensagem personalizada. Caso contrário, a função retornará o resultado da multiplicação do `input` por `2`. 

Se você quiser lançar uma mensagem de erro mais genérica, então pode referenciar o construtor `Error` assim:

```js
function divide(numerator, denominator) {
  if (denominator === 0) {
    throw new Error("Cannot divide by zero");
  }
  return numerator / denominator;
}
```

Aqui está um exemplo de uma função que verificará se o denominador é `0`. Se for esse o caso, então ele lançará uma mensagem de erro personalizada dizendo `Cannot divide by zero`.

Na próxima lição, veremos como lançar mensagens de erro dentro do contexto do bloco `try`/`catch` que é usado para tratar exceções de forma elegante em JavaScript.

# --questions--

## --text--

O que acontece quando você usa a declaração `throw` em JavaScript?

## --answers--

Ele continua o fluxo normal do programa.

### --feedback--

Pense em como o JavaScript reage quando não há tratamento de erros após um `throw`.

---

Ele lança uma expressão de erro e para o programa se nenhum manipulador de erro for encontrado.

---

Ele corrige o erro automaticamente.

### --feedback--

Pense em como o JavaScript reage quando não há tratamento de erros após um `throw`.

---

Ele registra o erro e prossegue com a próxima linha de código.

### --feedback--

Pense em como o JavaScript reage quando não há tratamento de erros após um `throw`.

## --video-solution--

2

## --text--

Como você pode garantir que o código funcione sem problemas após a ocorrência de um erro?

## --answers--

Use um loop para pular o erro.

### --feedback--

Pense em uma forma de capturar e tratar erros sem travar o programa.

---

Use a sintaxe `try…catch` para tratar o erro e permitir que a execução do código continue.

---

Use a instrução `throw` para pular o erro.

### --feedback--

Pense em uma forma de capturar e tratar erros sem travar o programa.

---

Pare o programa quando um erro for acionado.

### --feedback--

Pense em uma forma de capturar e tratar erros sem travar o programa.

## --video-solution--

2

## --text--

Como você usa a declaração `throw` em combinação com o construtor `error` no JavaScript?

## --answers--

`throw Error();`

### --feedback--

Pense em criar um novo objeto `Error` e lançá-lo.

---

`throw new Error();`

---

`Error throw();`

### --feedback--

Pense em criar um novo objeto `Error` e lançá-lo.

---

`new throw Error();`

### --feedback--

Pense em criar um novo objeto `Error` e lançá-lo.

## --video-solution--

2
