---
id: 6733bee844600f35c05b8264
title: How Does try...catch...finally Work?
challengeType: 11
videoId: _3whfUfxGYI
dashedName: how-does-try-catch-finally-work
---

# --description--

Watch the lecture video and answer the questions below.

# --questions--

## --text--

What best describes the `try` block?

## --answers--

It’s for running code again automatically after an error occurs.

### --feedback--

Think about the order of blocks in `try…catch…finally` statements, and the types of tasks each block handles.

---

It’s for handling errors.

### --feedback--

Think about the order of blocks in `try…catch…finally` statements, and the types of tasks each block handles.

---

It’s for setup before an error is thrown.

### --feedback--

Think about the order of blocks in `try…catch…finally` statements, and the types of tasks each block handles.

---

It’s a safe wrapper for code that might throw an error.

## --video-solution--

4

## --text--

Which block always executes even if an error occurs?

## --answers--

`try`

### --feedback--

This block is often used for cleanup tasks.

---

`catch`

### --feedback--

This block is often used for cleanup tasks.

---

`finally`

---

`throw`

### --feedback--

This block is often used for cleanup tasks.

## --video-solution--

3

## --text--

What is the purpose of the `catch` block?

## --answers--

To execute code that might throw an error.

### --feedback--

This block activates when something goes wrong in the `try` block.

---

To define a safe space for code execution.

### --feedback--

This block activates when something goes wrong in the `try` block.

---

To handle errors gracefully without crashing the program.

---

To always execute, regardless of errors.

### --feedback--

This block activates when something goes wrong in the `try` block.

## --video-solution--

3
