---
id: 6606b6b7760d0643c3b4eb29
title: Passo 19
challengeType: 20
dashedName: step-19
---

# --description--

Se o código dentro do bloco `try` gerar uma exceção, você deseja que o programa continue em execução e a instrução `pass` faz isso.

Embora esse código funcione, especificar o tipo de exceção após a palavra-chave `except` é considerado uma boa prática.

Como você sabe que um `ValueError` pode ser gerado, deixe um espaço após a palavra-chave `except` e adicione `ValueError` depois disso.

# --hints--

Você deve ter `except ValueError:` em seu código.

```js
({ test: () => assert(runPython(`_Node(_code).find_class("Board").find_function("find_empty_cell").find_for_loops()[0].find_bodies()[0].is_equivalent("try:\\n  col = contents.index(0)\\n  return row, col\\nexcept ValueError:\\n  pass")`)) })
```

# --seed--

## --seed-contents--

```py
class Board:
    def __init__(self, board):
        self.board = board
--fcc-editable-region--
    def find_empty_cell(self):
        for row, contents in enumerate(self.board):
            try:
                col = contents.index(0)
                return row, col
            except:
                pass
--fcc-editable-region--
puzzle = [
  [0, 0, 2, 0, 0, 8, 0, 0, 0],
  [0, 0, 0, 0, 0, 3, 7, 6, 2],
  [4, 3, 0, 0, 0, 0, 8, 0, 0],
  [0, 5, 0, 0, 3, 0, 0, 9, 0],
  [0, 4, 0, 0, 0, 0, 0, 2, 6],
  [0, 0, 0, 4, 6, 7, 0, 0, 0],
  [0, 8, 6, 7, 0, 4, 0, 0, 0],
  [0, 0, 0, 5, 1, 9, 0, 0, 8],
  [1, 7, 0, 0, 0, 6, 0, 0, 5]
]

gameboard = Board(puzzle)
```
